### ISSUE TITLE
Want to contribute

### ISSUE THREAD

**Issue by vbmade2000** [khonsulabs/pliantdb#35]
Project looks interesting to me. How can I start contributing to a project ? Where do I start from ?

**Comment by ecton** [comment]
Hi, thanks for checking the project out. There are a couple of issues I've labeled as potentially good first issues:

https://github.com/khonsulabs/pliantdb/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

I'm still pretty early on in the project's development, so over time I will try to add more. A lot of my planned features are simply planned in my head, so I need to spend more time trying to plan ahead to increase opportunities for contributions.

If there are any particular interests you have, let me know, and I can try to come up with ideas of things that might interest you.

**Comment by vbmade2000** [comment]
Sounds good. Will check issues.

**Comment by ecton** [comment]
I'm going to close this issue out. Glad to have you on the Discord, and I would love to have you contribute someday.

**Comment by vbmade2000** [comment]
Sure. I am sorry. I have been busy with work. Apology for not addressing the issue.

**Comment by ecton** [comment]
There's no need to apologize! I completely understand work and other life obligations getting in the way. 

I was cleaning up the issues in GitHub and didn't want to close it without commenting. I was thinking that when you were ready to work on an issue, such as ACME, we could assign that issue to you -- so I decided I could close this one out.
