### ISSUE TITLE
Revert hardcoded nightly version

### ISSUE THREAD

**Issue by ecton** [khonsulabs/pliantdb#46]
Code coverage started failing recently, and it appears that it's due to an ICE that dates back a little bit, but only recently started cropping up most likely due to rustfmt being broken on nightly for a while: [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/rust-lang/rust/84159)](https://github.com/rust-lang/rust/issues/84159). I tried to narrow it down, but I can't seem to get the ICE to occur outside of the project.

The earliest version of nightly that installed all the default components that doesn't cause an ICE is 2021-03-25.

The commit to revert is: cd668bf89752ba94bcd4b7382aaf2f6ffabb0177

**Comment by richkadel** [comment]
There was a recent change that landed in nightly just a couple of days ago that started causing an ICE for certain macro invocations. I suspect this is the issue you noticed.

I've submitted a pull request to fix it: #84456

It's approved and should be in nightly in a couple of days or so.

**Comment by ecton** [comment]
Thanks for the update, I can confirm that what I was whittling down seemed related to macros. And, more importantly, thank you for contributing a fix!
